name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: ['alpine:3.14', 'centos:7', 'centos:8', 'ubuntu:20.04']
        compiler: ['clang', 'gcc']
    container: ${{ matrix.image }}
    name: Build test (${{ matrix.image }}, ${{ matrix.compiler }})
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install tools
        uses: ./.github/actions/install-tools
      - name: Configure the project
        env:
          CC: ${{ matrix.compiler }}
        run: cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .
      - name: Build the project
        run: cmake --build .
  clang-format:
    runs-on: ubuntu-20.04
    name: Code style check
    steps:
      - name: Check coding style using clang-format
        run: clang-format --version
