name: Test branch
on: push

jobs:
  alpine:
    runs-on: ubuntu-20.04
    container: alpine:3.14
    name: Check /etc/issue
    steps:
      - name: List contents of /etc/issue
        run: cat /etc/issue
      - name: Create a file as root
        run: echo foo > /bar
      - name: Read the same file as root, see if it exists
        run: cat /bar
