name: Test branch
on: push

jobs:
  alpine:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: ['alpine:3.14', 'centos:7']
    container: ${{ matrix.image }}
    name: Build test (${{ matrix.image }})
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: get-cmake
        uses: lukka/get-cmake@latest
      - name: Check CMake version
        run: cmake --version
