name: Test branch
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: ['alpine:3.14', 'centos:7', 'centos:8', 'ubuntu:20.04']
    container: ${{ matrix.image }}
    name: Build test (${{ matrix.image }})
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install tools
        uses: ./.github/actions/install-tools
  clang-format:
    runs-on: ubuntu-20.04
    name: Code style check
    steps:
      - name: Check coding style using clang-format
        run: clang-format --version
