name: Test branch
on: push

jobs:
  alpine:
    runs-on: ubuntu-20.04
    container: alpine:3.14
    name: Check Alpine 3.14
    steps:
      - name: Check current working directory
        run: pwd
      - name: List contents of current directory
        run: ls -la
      - name: Check /github directory
        run: ls -laR /github
